-- ============================================================
-- Deploy Study Hub content to PST.PS_APPS_DEV
-- ============================================================
-- HOW TO RUN:
--   snow sql -f Scripts/deploy_study_hub.sql -c VCVDCXW-YD26998
--
-- BEFORE RUNNING: Upload files to stage first (see PUT commands below).
-- The PUT commands must be run from SnowSQL or Snowsight because
-- snow sql does not support PUT. Run from the project root directory:
--
--   snowsql -c VCVDCXW-YD26998 -r TECHNICAL_ACCOUNT_MANAGER
--
--   PUT file://Scripts/stage_data/cert_registry.json           @PST.PS_APPS_DEV.STUDY_HUB_STAGE/registry/           AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
--   PUT file://Scripts/stage_data/cert_domains.json            @PST.PS_APPS_DEV.STUDY_HUB_STAGE/domains/             AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
--   PUT file://Scripts/stage_data/cert_domain_tips.json        @PST.PS_APPS_DEV.STUDY_HUB_STAGE/domain_tips/         AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
--   PUT file://Scripts/stage_data/cert_questions_architect.json @PST.PS_APPS_DEV.STUDY_HUB_STAGE/questions/architect/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
--   PUT file://Scripts/stage_data/cert_review_notes_architect.json @PST.PS_APPS_DEV.STUDY_HUB_STAGE/notes/architect/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
--
-- Then run this SQL file to load from stage into tables.
-- ============================================================

USE ROLE TECHNICAL_ACCOUNT_MANAGER;
USE WAREHOUSE SNOWADHOC;

-- ── 1. CERT_REGISTRY ──
TRUNCATE TABLE IF EXISTS PST.PS_APPS_DEV.CERT_REGISTRY;

COPY INTO PST.PS_APPS_DEV.CERT_REGISTRY (
  CERT_KEY, NAME, CODE, FULL_NAME, CATEGORY, COLOR,
  SIDEBAR_GRADIENT, SIDEBAR_ACCENT, SIDEBAR_TEXT, SIDEBAR_SUB,
  DIFFICULTY, AVAILABLE, EXAM_INFO, DISPLAY_INFO, QUESTIONS_FILE
)
FROM (
  SELECT
    $1:CERT_KEY::VARCHAR,
    $1:NAME::VARCHAR,
    $1:CODE::VARCHAR,
    $1:FULL_NAME::VARCHAR,
    $1:CATEGORY::VARCHAR,
    $1:COLOR::VARCHAR,
    $1:SIDEBAR_GRADIENT::VARCHAR,
    $1:SIDEBAR_ACCENT::VARCHAR,
    $1:SIDEBAR_TEXT::VARCHAR,
    $1:SIDEBAR_SUB::VARCHAR,
    $1:DIFFICULTY::VARCHAR,
    $1:AVAILABLE::BOOLEAN,
    $1:EXAM_INFO::VARIANT,
    $1:DISPLAY_INFO::VARIANT,
    $1:QUESTIONS_FILE::VARCHAR
  FROM @PST.PS_APPS_DEV.STUDY_HUB_STAGE/registry/
)
FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE);

-- ── 2. CERT_DOMAINS ──
TRUNCATE TABLE IF EXISTS PST.PS_APPS_DEV.CERT_DOMAINS;

COPY INTO PST.PS_APPS_DEV.CERT_DOMAINS (
  CERT_KEY, DOMAIN_NAME, DOMAIN_DIR, COLOR, CSS_NUM, WEIGHT, SORT_ORDER
)
FROM (
  SELECT
    $1:CERT_KEY::VARCHAR,
    $1:DOMAIN_NAME::VARCHAR,
    $1:DOMAIN_DIR::VARCHAR,
    $1:COLOR::VARCHAR,
    $1:CSS_NUM::VARCHAR,
    $1:WEIGHT::VARCHAR,
    $1:SORT_ORDER::INT
  FROM @PST.PS_APPS_DEV.STUDY_HUB_STAGE/domains/
)
FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE);

-- ── 3. CERT_DOMAIN_TIPS ──
TRUNCATE TABLE IF EXISTS PST.PS_APPS_DEV.CERT_DOMAIN_TIPS;

COPY INTO PST.PS_APPS_DEV.CERT_DOMAIN_TIPS (
  CERT_KEY, DOMAIN_NAME, TIP_ORDER, TIP_TEXT
)
FROM (
  SELECT
    $1:CERT_KEY::VARCHAR,
    $1:DOMAIN_NAME::VARCHAR,
    $1:TIP_ORDER::INT,
    $1:TIP_TEXT::VARCHAR
  FROM @PST.PS_APPS_DEV.STUDY_HUB_STAGE/domain_tips/
)
FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE);

-- ── 4. CERT_QUESTIONS (architect) ──
DELETE FROM PST.PS_APPS_DEV.CERT_QUESTIONS WHERE CERT_KEY = 'architect';

COPY INTO PST.PS_APPS_DEV.CERT_QUESTIONS (
  CERT_KEY, QUESTION_ID, SOURCE, DOMAIN, QUESTION_TEXT,
  OPTIONS, CORRECT_INDICES, EXPLANATION, DIFFICULTY
)
FROM (
  SELECT
    $1:CERT_KEY::VARCHAR,
    $1:QUESTION_ID::VARCHAR,
    $1:SOURCE::VARCHAR,
    $1:DOMAIN::VARCHAR,
    $1:QUESTION_TEXT::VARCHAR,
    $1:OPTIONS::VARIANT,
    $1:CORRECT_INDICES::VARIANT,
    $1:EXPLANATION::VARCHAR,
    $1:DIFFICULTY::VARCHAR
  FROM @PST.PS_APPS_DEV.STUDY_HUB_STAGE/questions/architect/
)
FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE);

-- ── 5. CERT_REVIEW_NOTES (architect) ──
DELETE FROM PST.PS_APPS_DEV.CERT_REVIEW_NOTES WHERE CERT_KEY = 'architect';

COPY INTO PST.PS_APPS_DEV.CERT_REVIEW_NOTES (
  CERT_KEY, DOMAIN_NAME, LANG, CONTENT
)
FROM (
  SELECT
    $1:CERT_KEY::VARCHAR,
    $1:DOMAIN_NAME::VARCHAR,
    $1:LANG::VARCHAR,
    $1:CONTENT::VARCHAR
  FROM @PST.PS_APPS_DEV.STUDY_HUB_STAGE/notes/architect/
)
FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE);

-- ── Verify ──
SELECT 'CERT_REGISTRY' AS TBL, COUNT(*) AS ROWS FROM PST.PS_APPS_DEV.CERT_REGISTRY
UNION ALL
SELECT 'CERT_DOMAINS', COUNT(*) FROM PST.PS_APPS_DEV.CERT_DOMAINS
UNION ALL
SELECT 'CERT_DOMAIN_TIPS', COUNT(*) FROM PST.PS_APPS_DEV.CERT_DOMAIN_TIPS
UNION ALL
SELECT 'CERT_QUESTIONS', COUNT(*) FROM PST.PS_APPS_DEV.CERT_QUESTIONS
UNION ALL
SELECT 'CERT_REVIEW_NOTES', COUNT(*) FROM PST.PS_APPS_DEV.CERT_REVIEW_NOTES
ORDER BY TBL;
